version: "3.9"

services:
  db:
    image: postgres:15
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: testdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  api:
    build: ./server
    ports: 
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: testdb
